from __future__ import annotations

import html
from datetime import timezone

from .schema import AnalysisRecord, CandidatePortfolio, CandidateQuantResult


def selected_candidate(record: AnalysisRecord) -> CandidatePortfolio | None:
    sid = record.final.selected_candidate_id
    if not sid:
        return None
    return next((c for c in record.candidates.candidates if c.candidate_id == sid), None)


def selected_quant(record: AnalysisRecord) -> CandidateQuantResult | None:
    sid = record.final.selected_candidate_id
    if not sid:
        return None
    return next((q for q in record.quant_results if q.candidate_id == sid), None)


def _li(items: list[str]) -> str:
    return "".join(f"<li>{html.escape(x)}</li>" for x in items)


def build_html_report(record: AnalysisRecord) -> str:
    selected = selected_candidate(record)
    quant = selected_quant(record)
    created = record.created_at.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if selected:
        alloc_rows = "".join(
            f"<tr><td>{html.escape(a.ticker)}</td><td>{html.escape(a.name)}</td><td>{html.escape(a.asset_class)}</td><td>{a.weight:.2f}%</td><td>{html.escape(a.role)}</td></tr>"
            for a in selected.allocations
        )
    else:
        alloc_rows = '<tr><td colspan="5">Human review required - no candidate selected.</td></tr>'

    metric_html = ""
    if quant:
        m = quant.metrics
        metric_html = f"""
        <table><tr><th>Hist. ann. return</th><th>Hist. ann. vol</th><th>Sharpe</th><th>Max drawdown</th><th>95% daily CVaR</th></tr>
        <tr><td>{m.annualized_return_pct}</td><td>{m.annualized_volatility_pct}</td><td>{m.sharpe_ratio}</td><td>{m.max_drawdown_pct}</td><td>{m.cvar_95_daily_pct}</td></tr></table>
        <p class="small">Historical local calculation. Period: {html.escape(str(m.data_start))} to {html.escape(str(m.data_end))}. Not a forecast.</p>
        """

    fact_rows = "".join(
        f'<tr><td>{html.escape(i.status)}</td><td>{html.escape(i.claim)}</td><td>{html.escape(i.correction)}</td><td><a href="{html.escape(i.url)}">source</a></td></tr>'
        for i in record.factcheck.items
    )

    return f"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><title>Investment Committee Report</title>
<style>
body{{font-family:Arial,'Malgun Gothic',sans-serif;max-width:1050px;margin:40px auto;padding:0 24px;color:#1f2937;line-height:1.55}}
h1,h2{{color:#111827}} .badge{{display:inline-block;padding:4px 10px;border:1px solid #aaa;border-radius:999px;margin-right:6px}}
table{{border-collapse:collapse;width:100%;margin:12px 0 22px}} th,td{{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top}} th{{background:#f5f5f5}} .small{{font-size:12px;color:#666}} .warn{{padding:12px;border-left:4px solid #777;background:#f7f7f7}}
@media print{{body{{margin:12mm;max-width:none}}}}
</style></head><body>
<h1>Investment Committee Report</h1>
<p><span class="badge">Client {html.escape(record.client_profile.client_code)}</span><span class="badge">{created}</span><span class="badge">Decision: {html.escape(record.final.decision)}</span></p>
<div class="warn"><strong>Decision support only.</strong> {html.escape(record.compliance.disclaimer)}</div>
<h2>1. CIO decision</h2>
<p><strong>Selected candidate:</strong> {html.escape(record.final.selected_candidate_id or 'NONE')} &nbsp; <strong>Confidence:</strong> {record.final.confidence_pct}%</p>
<ul>{_li(record.final.rationale)}</ul>
<h2>2. Recommended allocation</h2>
<table><tr><th>Ticker</th><th>Name</th><th>Asset class</th><th>Weight</th><th>Role</th></tr>{alloc_rows}</table>
{metric_html}
<h2>3. Principal risks</h2><ul>{_li(record.final.principal_risks)}</ul>
<h2>4. Monitoring & rebalancing</h2><ul>{_li(record.final.monitoring_triggers)}</ul><p>{html.escape(record.final.rebalancing_rule)}</p>
<h2>5. Independent macro view</h2><p>{html.escape(record.macro.regime_summary)}</p><ul>{_li(record.macro.key_risks)}</ul>
<h2>6. Product research</h2><p>{html.escape(record.product.summary)}</p><ul>{_li([p.ticker + ' - ' + p.why_fit for p in record.product.products])}</ul>
<h2>7. Devil's advocate</h2><ul>{_li(record.bear.strongest_objections)}</ul><h3>Failure scenarios</h3><ul>{_li(record.bear.failure_scenarios)}</ul>
<h2>8. Fact check</h2><p>Overall: <strong>{html.escape(record.factcheck.overall_status)}</strong></p>
<table><tr><th>Status</th><th>Claim</th><th>Correction/note</th><th>Source</th></tr>{fact_rows}</table>
<h2>9. Suitability / process review</h2><p>Suitability: <strong>{html.escape(record.suitability.status)}</strong> &nbsp; Compliance: <strong>{html.escape(record.compliance.status)}</strong></p>
<h3>Missing information</h3><ul>{_li(record.suitability.missing_information)}</ul>
<h3>Required human checks</h3><ul>{_li(record.compliance.required_human_checks)}</ul>
<p class="small">Generated by a local decision-support application. Historical metrics may be incomplete due to market-data availability. Verify all client-facing facts and applicability of firm policy/law before use.</p>
</body></html>"""
